### ISSUE TITLE
Manual download of oc binary for Minishift is not required.

### ISSUE THREAD

**Issue by LalatenduMohanty** [openshift-evangelists/kbe#10]
We do not need to download the `oc` binary as Minishift downloads a copy of it and we can reuse it through `minishift oc-env` command. We should the the existing steps [1] as below.

```
1. Install [Minishift](https://docs.openshift.org/latest/minishift/getting-started/installing.html)
2. Run `minishift start`
3. Run `minishift oc-env` and do as suggested in the output of the command
4. Log in using oc login -u system:admin with password admin
5. Create a symlink from `oc` like so:  `ln -s `which oc` kubectl`
```

[1] https://github.com/openshift-evangelists/kbe/blob/master/content/page/diy.md

**Comment by LalatenduMohanty** [comment]
` $ minishift oc-env is available from minishift 1.0.0 version.

**Comment by mhausenblas** [comment]
Excellent observation @LalatenduMohanty , I wasn't aware of it. Do you plan to send in a PR to fix that or …?

**Comment by budhrg** [comment]
I was about to create issue and found this :+1:

**Comment by LalatenduMohanty** [comment]
@mhausenblas I will send the PR, but I am going through the examples and make sure these work on Minishift 1.0.0 or 1.0.1 version.

**Comment by mhausenblas** [comment]
Cool, thanks, yeah that makes sense @LalatenduMohanty.

**Comment by ryanj** [comment]
Thanks for the issue.  

Given #63, I think we're going to try to avoid using `oc` in examples here, in an effort to make the content as portable as possible.  It's no longer mentioned on the `diy` page
