### ISSUE TITLE
PersistentVolumeClaim/PersistentVolume example

### ISSUE THREAD

**Issue by r0fls** [openshift-evangelists/kbe#16]
Thanks for making this, it's awesome. It says in the volumes section:

>A special type of volume is PersistentVolume, which we will cover elsewhere.

I can't find that anywhere though, so I'm just raising an issue here with the enhancement request.

**Comment by mhausenblas** [comment]
Thanks and very good point!

**Comment by yvzsrt** [comment]
In pv page, it is assumed that the system has a suaitable pv. It would be good to add a pv.yaml as a first step.
In the example pvc listed as bound but for us it is listed as pending.
Very useful tutorials. Thanks a lot.
