### ISSUE TITLE
Pod description innacurate

### ISSUE THREAD

**Issue by johnfosborneiii** [openshift-evangelists/kbe#19]
The pod description says that containers in a pod share the mount namespace which is false. Containers have their own file systems. In order to see each other's directories they need to use a shared Volume with EmptyDir or other

**Comment by mhausenblas** [comment]
Thanks for the feedback @johnfosborneiii.

> The pod description says that containers in a pod share the mount namespace which is false.

I assume you're referring to the introductory paragraph where it says:

> A pod is a collection of containers sharing a network and mount namespace and is the basic unit of deployment in Kubernetes. All containers in a pod are scheduled on the same node.

Note that the goal of KBE is not to define the exact inner workings of components but to teach people how to use Kubernetes. While above is terse it is technically correct.

> Containers have their own file systems.

This is correct but has nothing to do with the statement.


> In order to see each other's directories they need to use a shared Volume with EmptyDir or other

This is also correct and doesn't contradict with what I wrote above. Yes, if you want to share data via volumes then each participating container has to mount it into its filesystem. Do they share a networking and mount *namespace* without user intervention? Yes.

Here's how it works (simplified):

- The kubelet runtime is the responsible entity for launching pods/containers.
-  [On start](https://github.com/kubernetes/kubernetes/blob/886e04f1fffbb04faf8a9f9ee141143b2684ae68/pkg/kubelet/kuberuntime/kuberuntime_container.go#L102), for each container you can see that the [mounts are created](https://github.com/kubernetes/kubernetes/blob/886e04f1fffbb04faf8a9f9ee141143b2684ae68/pkg/kubelet/kuberuntime/kuberuntime_container.go#L194) automatically.
- The [infrastructure container](https://github.com/kubernetes/kubernetes/blob/master/build/pause/pause.c) is responsible for keeping up the namespaces across individual containers in a pod re-starting.

Does this help?

**Comment by mhausenblas** [comment]
@johnfosborneiii can I close this?

**Comment by johnfosborneiii** [comment]
Sorry for the delay, I've been on leave. This topic has actually been something that's confused me for a little while because none of the public facing Kubernetes documentation shows which Linux Namespaces are shared between containers in a pod. I always assumed that each container in a pod had their own mount namespace since they can't see each other's files without mounting a volume. To be honest, this is still a little unclear to me, but it makes sense because using a single volume wouldn't work in different mount namespaces unless you had a read-write-many access mode.

It would be nice if there was a table somewhere showing which Linux Namespaces are specific to a container and which are specific to a pod.

My current understanding is is that a Linux Container started by Moby/Docker standalone would have it's own:
- mount
- uts
- pid
- network
- ipc
- cgroups

Inside of Kubernetes, Linux Containers in the same pod would share:
- network
- mount
- ipc (shared memory)
- cgroups

Inside of Kubernetes, Linux Containers in the same pod would have their own:
- uts
- pid
- user (future release)
- cgroups (limits can be set at the pod or container level)

Am I on target?

**Comment by mhausenblas** [comment]
I think that what you described makes sense to me. On the other hand, the idea behind KBE is not a deep dive into all the implementation details of K8S but providing concrete usage examples. So, what I'd suggest concerning:

> It would be nice if there was a table somewhere showing which Linux Namespaces are specific to a container and which are specific to a pod.

Maybe you want to blog about it and we link to it once it's published. I'm worried about being inconsistent, that is, covering one specific topic in great detail while others not so much. Hope this makes sense?

**Comment by johnfosborneiii** [comment]
Makes total sense, I wasn't suggesting you add it to the page, was just asking since you seem to know better than me. Go ahead and close the ticket!
