### ISSUE TITLE
Should we display the yaml on the page

### ISSUE THREAD

**Issue by budhrg** [openshift-evangelists/kbe#22]
Hi @mhausenblas ,

I was wondering that displaying the yaml configuration on the page would help the user to easily view the configuration up front instead of clicking on that hyperlink and refer.

Check the following screenshot.
![screenshot from 2017-09-09 23-36-09](https://user-images.githubusercontent.com/1132451/30242638-c09a72d8-95b7-11e7-9350-790a531f801a.png)

Also, it would  help user to copy and create a yaml file and run it manually which will help user to understand better than `kubectl create -f <remote url>` approach.

Let me know what is your opinion on it.

BTW, I am working on #4 and found that I need to go to the URL to understand the configuration file properly. Though, `kubectl create -f <remote-url>` approach seems quite easy to go through with demo but it seems the configuration info fade way from mind as well.

**Comment by mhausenblas** [comment]
I'm unsure what the advantage would be (since it's just a click away) and the additional effort would be clear: we would need to maintain it in two places so overall I'm not really convinced.

**Comment by budhrg** [comment]
> we would need to maintain it in two places so overall I'm not really convinced.

Sure no problem. Thanks.
