### ISSUE TITLE
Next/Previous links is not present in published KBE website

### ISSUE THREAD

**Issue by budhrg** [openshift-evangelists/kbe#25]
Hi @mhausenblas ,

The PR for Previous/next is merged but it seems the website is not updated yet.

![screenshot from 2017-09-17 10-03-08](https://user-images.githubusercontent.com/1132451/30518019-7062902e-9b8f-11e7-8aeb-8bc404a75d65.png)

**Comment by mhausenblas** [comment]
Argh, yeah, thanks for the reminder. Need to rebuild the site ;)

**Comment by mhausenblas** [comment]
OK, done and thanks again @budhrg!

**Comment by budhrg** [comment]
Verified. Working fine now :+1:
