### ISSUE TITLE
Scrub mhausenblas/* images and manifests

### ISSUE THREAD

**Issue by ahmetb** [openshift-evangelists/kbe#32]
@mhausenblas

**Comment by mhausenblas** [comment]
Thanks @ahmetb!

**Comment by ryanj** [comment]
- [ ] git status
- [ ] git checkout master
- [ ] git pull origin master
- [ ] git branch quay
- [ ] git checkout quay
- [ ] grep -lsir mhausenblas .
- [ ] sed -i -e 's/github.com\/mhausenblas\/simpleservice/github.com\/openshift-labs\/simpleservice/' content/page/envs.md
- [ ] sed -i -e 's/hub\.docker\.com\/r\/mhausenblas\/simpleservice/quay.io\/repository\/openshiftlabs\/simpleservice/' content/page/pods.md
- [ ] sed -i -e 's/mhausenblas/openshiftlabs/' content/page/statefulset.md
- [ ] grep -lsir mhausenblas . | xargs sed -i -e 's/mhausenblas/quay.io\/openshiftlabs/'
- [ ] git diff
- [ ] git status
- [ ] git add 
- [ ] git commit -m ''
- [ ] git push ryanj quay

**Comment by ryanj** [comment]
PR ready, needs testing: https://github.com/openshift-evangelists/kbe/pull/47
