### ISSUE TITLE
Dou you consider adding multiple language support?

### ISSUE THREAD

**Issue by ykocaman** [openshift-evangelists/kbe#35]
Your tutorials are so perfect!  Firstly, thanks a lot! I want to translate this pages as Turkish, what can i do?  Do you consider adding multiple language, so we can send PR for other languages than English. Otherwise, I have to register new domain and clone kubernetesbyexample.com in my native language. Then i will give a reference by the link.

**Comment by Rwing** [comment]
Yep, is there schedule to support multiple language?

**Comment by jankleinert** [comment]
There is not a schedule, but we are looking into the possibility of adding support for multiple languages

**Comment by ryanj** [comment]
Thanks for the suggestion @ykocaman.  
We don't have the bandwidth to implement i18n/L10n currently, but we will try to add it into the roadmap in the future.

Closing this issue for now...
