### ISSUE TITLE
Update the examples to Minishift version 1.0.0

### ISSUE THREAD

**Issue by budhrg** [openshift-evangelists/kbe#4]
We have now [Minishift 1.0.0](https://github.com/minishift/minishift/releases/tag/v1.0.0) released around 10 days ago.

Also, it uses the OpenShift version `1.5.0` which has Kubernetes `1.5.2`.

Happy to look into it :smile:

**Comment by mhausenblas** [comment]
Good idea! We have to think about how to handle different versions. Things to consider, OTTOMH, might be other stuff too:

- one branch per version? is there a better way?
- how to make it work nicely in Hugo (showing latest version as the default, how to switch between versions?)

Would you like to come up with a design suggestion here @budhrg?

**Comment by budhrg** [comment]
> We have to think about how to handle different versions.

+1 Would be good to have.

> one branch per version? is there a better way?
> how to make it work nicely in Hugo (showing latest version as the default, how to switch between versions?)

Need to do bit of investigation here. Not much experience in Hugo ATM.

> Would you like to come up with a design suggestion here 

Sure :+1:

**Comment by mhausenblas** [comment]
Want me to assign this to you @budhrg?

**Comment by budhrg** [comment]
Sure @mhausenblas
