### ISSUE TITLE
http/https issue on http://kubernetesbyexample.com/ 

### ISSUE THREAD

**Issue by markusjnagel** [openshift-evangelists/kbe#43]
Hi there,

probably a misconfigured route (if running on OpenShift, which I assume):

Going to [http://kubernetesbyexample.com/](http://kubernetesbyexample.com/) opens KBE in all its beauty while using [the https variant](https://kubernetesbyexample.com/) only shows the home link (the http version)...
Not really a huge issue, but since everyone is immediately suspicious these days about non-encrypted pages.... ;-)

Cheers!

**Comment by simongottschlag** [comment]
I’ve only looked at it with my phone, but my best guess is that all links to content is based on this config:
https://github.com/openshift-evangelists/kbe/blob/05a59c1a1f01b13fc22c71350fcb6e31309dc01a/config.toml#L1

That means it will try to load http content when you’re visiting a https site. I’d recommend updating the config to https and then doing a http to https redirect for all http requests. Adding HSTS would be great as well!

**Comment by jankleinert** [comment]
Thanks for pointing this out - it has been updated to use https for the base URL and to default to https.
