### ISSUE TITLE
test coverage v1 - local tests

### ISSUE THREAD

**Issue by ryanj** [openshift-evangelists/kbe#53]
See #52 for Epic details

v1: local content validation (BYO cluster credentials)
- [x] find all markdown files, foreach file{
- [x] parse and extract example commands
- [ ] parse example responses
- [ ] establish test cases to ensure commands do not fail or return an error when executed in order
- [ ] add test cases to compare example response output with actual response output, report any diffs

**Comment by jboxman** [comment]
@ryanj, the upstream k8s docs GitHub repo last I looked actually has code that unit tests their examples, I think. Maybe that can be reused here?

**Comment by ryanj** [comment]
Thanks, good idea. I'll take a look

**Comment by ryanj** [comment]
notes on using Jest for this: https://testautomationu.applitools.com/jest-testing-tutorial/chapter3.html
