### ISSUE TITLE
No cleanup steps in some chapters

### ISSUE THREAD

**Issue by anubhavcodes** [openshift-evangelists/kbe#66]
Hello openshift-evangelists/kbe maintainers, 

First of all, thank you for such a great online resource. The examples are crisp, clear and easy to follow. Specially the fact that your tutorial doesn't have a yaml file in the tutorial itself, but linked to another page, makes following the tutorials even easier. 

One small nitpick I noticed that from chapters StatefulSets, we have stopped including cleanup code at the end. Is this intentional? If not would you like to have a PR to include cleanup steps? I would be very happy to contribute.

**Comment by ryanj** [comment]
Thank you,  Anubhav!
I'd definitely accept a PR for these changes.

**Comment by anubhavcodes** [comment]
Thanks, I will prepare a PR soon.

**Comment by ryanj** [comment]
Changes should be available on the main site.  Thanks!
