### ISSUE TITLE
Content doesn't explain how to run commands inside the cluster

### ISSUE THREAD

**Issue by brephophagist** [openshift-evangelists/kbe#9]
In both the pod and deployment documents, the simple example service is validated with cURL commands running "from inside the cluster", e.g.

> Let’s verify that from within the cluster (using kubectl describe first to get the IP of one of the pods):
> ```
>  [cluster] $ curl 172.17.0.3:9876/info
>  {"host": "172.17.0.3:9876", "version": "0.9", "from": "172.17.0.1"}
>```

but no explanation is given as to how exactly to do this.

(FWIW, I am running minishift locally, so if it's an obvious feature in hosted OpenShift some clarification may be all that's necessary.)

**Comment by mhausenblas** [comment]
True, that can be improved. See for example PR https://github.com/openshift-evangelists/kbe/pull/6

**Comment by brephophagist** [comment]
Ah, my mistake - should have reviewed PRs! Will close.
